fix(worker): NPE on worker shutdown
Fixes a small NullPointerException while server is shutting down.

```
Exception in thread "Worker.failsafeRegistration"
java.lang.NullPointerException: Cannot invoke "io.grpc.Server.isShutdown()" because "this.this$0.server" is null
     at build.buildfarm.worker.shard.Worker$1.run(Worker.java:521)
     at java.base/java.lang.Thread.run(Thread.java:1583)
```