Disable rules_docker transitions (#1648)
This PR fixes the issues introduced by setting default bazel version to 7, which is now breaking CI.

Example errors:

in constraint_values attribute of platform rule @@io_bazel_rules_docker//platforms:image_transition: '@@io_bazel_rules_docker//platforms:image_transition_cpu' does not have mandatory providers: 'ConstraintValueInfo'

Analysis of target '@@io_bazel_rules_docker//platforms:image_transition' failed
ERROR: /home/yuriyb/bazel-buildfarm/BUILD:119:11: Target @@io_bazel_rules_docker//platforms:image_transition was referenced as a platform, but does not provide PlatformInfo