[Worker] Catch all in ReportStage
I've got a situation where a worker is missing directories upon tearing down an
action. When it throws an exception the worker becomes stuck forever. This
makes it more resilient to benign errors and catches them all for safety to
prevent a worker being wedged.

I get the stack:
```
SEVERE: ReportResultStage::run(): stage terminated due to exception
java.lang.IllegalStateException: inputDirectory dbbcb4da7a1858c1debab42054b872a60a64072fe34349b01047e5930d2e3721/79 is not in directoryStorage
        at build.buildfarm.cas.cfc.CASFileCache.decrementReferencesSynchronized(CASFileCache.java:1651)
        at build.buildfarm.cas.cfc.CASFileCache.decrementReferences(CASFileCache.java:1612)
        at build.buildfarm.worker.shard.CFCExecFileSystem.destroyExecDir(CFCExecFileSystem.java:444)
        at build.buildfarm.worker.shard.ShardWorkerContext.destroyExecDir(ShardWorkerContext.java:719)
        at build.buildfarm.worker.ReportResultStage.after(ReportResultStage.java:203)
        at build.buildfarm.worker.PipelineStage.iterate(PipelineStage.java:129)
        at build.buildfarm.worker.PipelineStage.runInterruptible(PipelineStage.java:44)
        at build.buildfarm.worker.PipelineStage.run(PipelineStage.java:51)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

As a side note, I've been looking to insulate against this case on an
ephemeral macOS VM stack. The healthcheck endpoint seems like a
reasonable place we could test pipeline status; but right now something
like this seems to take the worker down for the count!