Improve error message for invalid hashes. (#99)
In case client and server are not using the same
digest hash function, server would fail with a message
like:
```
java.lang.NumberFormatException: Invalid hash size
```

PR changes the error message to make it clear which algorithm
was expected on the server side and which hash was checked:
```
java.lang.NumberFormatException: [8029246214105a97ea1eb37977679dab8a238f80d2d4ca4980f142f669b4bbce] is not a valid MD5 hash.
```

This is very useful for people trying to setup build farm
infra for the first time. This is especially useful, since
Bazel has changed the default digest hash from MD5 to SHA256,
but looks like BuildServer is expecting MD5.